server:
  port: 8090
spring:
  application:
    name: music_system
  datasource:
    url: ${sqlurl}
    driver-class-name: com.mysql.jdbc.Driver
    username: ${username}
    password: ${password}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher   #集成swagger-ui需要
  jpa:
    show-sql: true
  redis:
    port: 6379
    host: ${redis.host}
    password: ${password}
  mail:
    host: smtp.qq.com
    port: 465
    username: ${email.number}
    password: ${email.password}
    default-encoding: UTF-8
    protocol: smtps
    nickname: 音乐系统
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    solr:
      host: ${solr.host}
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出Sql语句执行日志
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:com/chen/music/mapper/xml/*.xml

music.system.image.save-path-img: ${save-path-img}
music.system.music.save-path-music: ${save-path-music}
music.system.image.default-avatar: default_avatar.png

#2MB
music.system.image.max-size: 2097152
music.system.music.max-size: 104857699

#email.number: ${email.number}
#email.password: ${email.password}